### ISSUE TITLE
2022.1.4导入出错

### ISSUE THREAD

**Issue by irezm** [xinhochen/free-mybatis-plugin#1]
具体版本Build #IU-221.6008.13, built on July 19, 2022

系统版本win10

3月份与7月份安装时均报错
能力有限未找到具体错误日志

**Comment by xinhochen** [comment]
这个插件没有导入功能，不知道这个“导入出错”是指的什么地方的导入？

**Comment by irezm** [comment]
> 这个插件没有导入功能，不知道这个“导入出错”是指的什么地方的导入？

当时可能没表述清楚，导入到idea报错，具体错误忘记了，现在使用Free MyBatis Tool了

当时可能是我使用的idea版本不兼容导致的，我使用低版本idea安装是成功的
